default: &default
  site_share_url_pattern: 'http://localhost:3000/desktop/share/sites/:id'
  product_share_url_pattern: 'http://localhost:3000/desktop/share/products/:id'
  system_rooms: ['小区广场', '业委会', '物业圈', '吐槽圈', '互助圈', '亲子圈', '敬老圈', '宠物圈', '棋艺圈']
  service_banners:
    - src: http://ot7w18mwp.bkt.clouddn.com/ban-3.jpg
      url:
    - src: http://ot7w18mwp.bkt.clouddn.com/ban-2.jpg
      url:
    - src: http://ot7w18mwp.bkt.clouddn.com/ban-1.jpg
      url:
  app_version_message:
    version_number: 2.1.3
    download_url: http://....
development:
  <<: *default
test:
  <<: *default
production:
  <<: *default
  site_share_url_pattern: 'http://www.imolin.cn/desktop/share/sites/:id'
  product_share_url_pattern: 'http://www.imolin.cn/desktop/share/products/:id'
