default: &default
  site:
    name: 淘美客
    host: http://api.mokomo.cn
    copyright: © ToMoKo All Right Reserved 2017
    description: 淘美客是一家提供在线美容预约服务的私享平台，专业打造优质舒适的社区美容服务，丰富多样的美容项目、各有所长的美容技师供您自由选择。
    slogan: 定制私人美容，想约就约放心选择
  email:
    sender: admin@tanmer.com
  weixin:
    app_id: wx2112a27b1c8bb766
    app_secret: d4624c36b6795d1d99dcf0547af5443d
    token_string: 50c2263e7f076bbe75c50ebd54401963 # 微信Token值
    secret_string: 0abcf2c591b0a1b209ca12a20a8eda83 # 微信服务URL配置中，此值用来避免真正使用的Token值暴露在URL上，提高安全性。
    encoding_aes_key:
  weixin_open_app: # 微信开放平台绑定的APP
    app_id:
    app_secret:
  weixin_login:
    appid: wx2112a27b1c8bb766 # 微信扫码登录的公众号appid
    host: 'https://wxopen.tanmer.com'
  sms:
    provider: yun_pian_v1
    yun_pian_v1:
      api_key: c97380fa188341572c1bcdadf383dfc2
    templates:
      order_succeed_to_user: "【淘美客】恭喜你下单成功，商家(#site_name#)商家电话(#phone#)"
      order_succeed_to_agent: "【淘美客】新增用户订单，金额(#price#)，请及时登录商家后台处理"
      order_completed_to_user: "【淘美客】您的(#order_code#)号订单已#from#确认收货,如有疑问您可以进行申诉"
  mobile:
    auth_token_template: "【淘美客】您的验证码是#code#。如非本人操作，请忽略本短信。"

  payment: # Ping++支付
    api_id: app_yDm5S4uv9SOG8CWb
    api_key: sk_live_mDyHWHybjjfHifjT0KfvfTm9
    channels:
    - alipay
    - wx
    enable_pingpp_one: false

  qiniu: &qiniu_credentials
    access_key: HXrvQOeDfAizpMzdanxSMiotX60zWuDXAseybFcx
    secret_key: n886ogK5IGUwYx-M4m-NLSaP0-OTGD2_eCCsqId_

  paperclip:
    enable: true
    options:
      storage: :qiniu
      qiniu_credentials:
        <<: *qiniu_credentials
      bucket: tmf
      use_timestamp: false
      qiniu_host: ocwr8qu9g.bkt.clouddn.com

  test_account:
    mobile_phone: '13900000000'
    code: '000000'
development:
  <<: *default
production:
  <<: *default
test:
  <<: *default
