require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.
RSpec.describe Agent::MemberNotesController, type: :controller do
  # This should return the minimal set of attributes required to create a valid
  # MemberNote. As you add validations to MemberNote, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    attributes_for(:member_note)
  }
  let(:invalid_attributes) {
    attributes_for(:member_note)
  }
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Agent::MemberNotesController. Be sure to keep this updated too.

  login_admin
  # login_user
  # login_agent

  describe "GET #index" do
    it "returns a success response" do
      member_note = create(:member_note)
      get :index
      expect(response).to be_success
    end
  end

  describe "GET #show" do
    it "returns a success response" do
      member_note = create(:member_note)
      get :show, params: {id: member_note.to_param}
      expect(response).to be_success
    end
  end

  describe "GET #new" do
    it "returns a success response" do
      get :new, params: {}
      expect(response).to be_success
    end
  end
  describe "GET #edit" do
    it "returns a success response" do
      member_note = create(:member_note)
      get :edit, params: {id: member_note.to_param}
      expect(response).to be_success
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new MemberNote" do
        expect {
          post :create, params: {member_note: valid_attributes}
        }.to change(MemberNote, :count).by(1)
      end

      it "redirects to the created agent_member_note" do
        post :create, params: {member_note: valid_attributes}
        expect(response).to redirect_to(agent_member_note_url(MemberNote.last))
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'new' template)" do
        post :create, params: {member_note: invalid_attributes}
        expect(response).to be_success
      end
    end
  end
  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }
      it "updates the requested agent_member_note" do
        member_note = create(:member_note)
        put :update, params: {id: member_note.to_param, member_note: new_attributes}
        member_note.reload
        skip("Add assertions for updated state")
      end
      it "redirects to the agent_member_note" do
        member_note = create(:member_note)
        put :update, params: {id: member_note.to_param, member_note: valid_attributes}
        expect(response).to redirect_to(agent_member_note_url(member_note))
      end
    end
    context "with invalid params" do
      it "returns a success response (i.e. to display the 'edit' template)" do
        member_note = create(:member_note)
        put :update, params: {id: member_note.to_param, member_note: invalid_attributes}
        expect(response).to be_success
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested agent_member_note" do
      member_note = create(:member_note)
      expect {
        delete :destroy, params: {id: member_note.to_param}
      }.to change(MemberNote, :count).by(-1)
    end
    it "redirects to the agent_member_notes list" do
      member_note = create(:member_note)
      delete :destroy, params: {id: member_note.to_param}
      expect(response).to redirect_to(agent_member_notes_url)
    end
  end
end
