default: &default
  adapter: postgresql
  username: postgres
  password: '123456'
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['DATABASE_HOST'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") %>_dev
test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") %>_test
production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") %>
