source 'https://gems.ruby-china.org'

ruby '2.3.4'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end

source 'https://gems.tanmer.com' do
  gem 'tmf_common', '0.0.5'
  gem 'sms_service', '0.0.4.tanmer'
end

gem 'devise', '~> 4.2', '>= 4.2.1'
gem 'omniauth-oauth2', '~> 1.4'
gem 'omniauth-gitlab', '~> 1.0', '>= 1.0.2'
gem 'doorkeeper', '~> 4.2.5'
gem 'slim-rails', '~> 3.1', '>= 3.1.2'
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.1.1'
gem 'webpacker', '~> 3.2', '>= 3.2.1'
# Use postgresql as the database for Active Record
gem 'pg', '~> 0.18'
# Use Puma as the app server
gem 'puma', '~> 3.0'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
# gem 'jquery-rails'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development
gem 'figaro', '~> 1.1', '>= 1.1.1'
gem 'simple_form', '~> 3.5'
gem 'bootstrap-sass', '~> 3.3.6'
gem 'jwt', '~> 1.5', '>= 1.5.6'
gem 'rack-cors', '~> 1.0', '>= 1.0.1'
gem 'rails-i18n', '~> 5.0.0'
gem 'doorkeeper-i18n'
gem 'simple-navigation', '~> 4.0.5'
gem 'font-awesome-sass'
gem 'rails-i18n-generator'
gem 'cancancan', '~> 2.0'

gem 'redis-namespace', '~> 1.6'
gem 'kaminari', '~> 1.1', '>= 1.1.0'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
  gem 'pry-rails'
  gem 'rspec-rails', "~> 3.5"
  gem 'shoulda-matchers', '~> 3.1', '>= 3.1.2'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '~> 3.0.5'
  gem 'guard', '~> 2.14', '>= 2.14.1'
  gem 'guard-rails', '~> 0.8.0', require: false
  gem 'guard-bundler', '~> 2.1', require: false
  gem 'guard-livereload', '~> 2.5', '>= 2.5.2', require: false
  gem 'guard-rspec', '~> 4.7', '>= 4.7.3', require: false

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'

  # gem 'capistrano', '~> 3.6'
  # gem 'capistrano-rvm'
  # gem 'capistrano-bundler', '~> 1.2'
  # gem 'capistrano-rails', '~> 1.2'
  # gem 'capistrano3-puma', '~> 3.1', github: "seuros/capistrano-puma"
end
