var Vue = require("vue");
Vue.components = {};
// Vue.components.Hello = Vue.component('hello', require("./hello"))
Vue.components.Loading = Vue.component('loading', require("./loading"))
Vue.components.ImageUpload = Vue.component('image-upload', require('./image_upload'));
Vue.components.ImageAlbum = Vue.component('image-album', require('./image_album'));
Vue.components.Modal = Vue.component('modal', require('./modal'));
Vue.components.ImageSelect = Vue.component('image-select', require('./image_select'));
Vue.components.CatalogList = Vue.component('catalog-list', require('./catalog'))
Vue.components.MultiImageUpload = Vue.component('multi-image-upload', require('./multi_image_upload'));
Vue.components.ShowImage = Vue.component('show-image', require('./show_image'));
Vue.components.ShareModal = Vue.component('share-modal', require('./share_modal'));
